# Generated by Django 5.2.7 on 2025-10-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.png', null=True, upload_to='profile_pics/'),
        ),
    ]
