# Generated by Django 5.2.7 on 2025-11-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_tracker', '0002_focuslog_humidity_focuslog_temperature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_seen_security_update',
            field=models.BooleanField(default=False),
        ),
    ]
