# Generated by Django 5.2.7 on 2025-11-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_tracker', '0003_profile_has_seen_security_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='focuslog',
            name='emotion_detected',
            field=models.CharField(choices=[('Neutral', 'Neutral'), ('Happy', 'Happy'), ('Sad', 'Sad'), ('Angry', 'Angry'), ('Surprise', 'Surprise'), ('Fear', 'Fear'), ('Disgust', 'Disgust'), ('No Face', 'No Face'), ('No ROI', 'No ROI')], default='No Face', max_length=20),
        ),
        migrations.AlterField(
            model_name='focuslog',
            name='status',
            field=models.CharField(choices=[('FOCUSED', 'Focused'), ('DISTRACTED', 'Distracted'), ('DROWSY', 'Drowsy'), ('NO FACE', 'No Face')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
