# Generated by Django 5.2.7 on 2025-12-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_tracker', '0005_device_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='focuslog',
            name='manual_correction',
            field=models.BooleanField(default=False, verbose_name='Manually Corrected'),
        ),
    ]
