# Generated by Django 5.2.7 on 2025-12-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_tracker', '0006_focuslog_manual_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='consent_agreed',
            field=models.BooleanField(default=False, verbose_name='Agreed to Privacy Policy'),
        ),
        migrations.AddField(
            model_name='profile',
            name='consent_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
