# Generated by Django 5.2.7 on 2026-01-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_tracker', '0007_profile_consent_agreed_profile_consent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(default='Raspberry Pi Unit', max_length=100),
        ),
    ]
